# Simulator configuration parameters
  /unicycle_kin_sim/dt: 0.001                   # Integration step

# Vehicle initial state
  /unicycle_kin_sim/x0: 0.0                     # Initial position x
  /unicycle_kin_sim/y0: 0.0                     # Initial position y
  /unicycle_kin_sim/theta0: 0.0                 # Initial heading

# Controller parameters
  /unicycle_kin_trajctrl/P_dist: 0.05           # Distance of point P from odometric center
  /unicycle_kin_trajctrl/K: 0.1                 # PD trajectory tracking controller gain

# Controller configuration parameters
  /unicycle_kin_trajctrl/run_period: 0.01       # Node execution period

