# Simulator configuration parameters
  /unicycle_dyn_sim/dt: 0.001                       # Integration step

# Vehicle parameters
  /unicycle_dyn_sim/m: 2.0                          # Vehicle mass
  /unicycle_dyn_sim/I: 0.030                        # Yaw moment of inertia


# Vehicle initial state
  /unicycle_dyn_sim/x0: 0.0                         # Initial yaw rate
  /unicycle_dyn_sim/y0: 0.0                         # Initial sideslip
  /unicycle_dyn_sim/theta0: 0.0                     # Initial position x
  /unicycle_dyn_sim/v0: 0.0                         # Initial position y
  /unicycle_dyn_sim/omega0: 0.0                     # Initial heading

