# Simulator configuration parameters: dynamics
  /car_sim/tyre_model: 0                 # Tyre model (0, linear; 1, fiala with saturation; 2, fiala without saturation)

  /car_sim/dt: 0.001                       # Integration step

# Vehicle parameters
  /car_sim/m: 1.5                          # Vehicle mass
  /car_sim/cog_a: 0.14                     # Distance of COG from front axle
  /car_sim/cog_b: 0.12                     # Distance of COG from rear axle
  /car_sim/mu: 0.385                       # Ground friction coefficient
  /car_sim/Cf: 50.0                        # Front cornering stiffness
  /car_sim/Cr: 120.0                       # Rear cornering stiffness
  /car_sim/Iz: 0.023                       # Yaw moment of inertia


# Vehicle initial state
  /car_sim/r0: 0.0                         # Initial yaw rate
  /car_sim/beta0: 0.0                      # Initial sideslip
  /car_sim/x0: 0.0                         # Initial position x
  /car_sim/y0: 0.0                         # Initial position y
  /car_sim/psi0: 0.78                      # Initial heading (0.0 for test simple)

  /car_sim/Fyf_max: 0.0
  /car_sim/Fyr_max: 0.0

# ------------------------------------------------------------------------------------------------------------------------
# Simulator configuration parameters: kinematics

  /bicycle_sim/dt: 0.001                       # Integration step

# Vehicle parameters
  /bicycle_sim/L: 0.26                     # Vehicle length

# Vehicle initial state
  /bicycle_sim/x0: 0.0                     # Initial position x
  /bicycle_sim/y0: 0.0                     # Initial position y
  /bicycle_sim/theta0: 0.78                # Initial heading


